### ISSUE TITLE
Elemental creatures animroot error messages

### ISSUE THREAD

**Issue by plenarius** [pstemarie/Neverwinter_Dark_Ages#12]
The Air, Fire and Water elementals produce the following error message when created

`The model's animroot node must match the name of an existing node in the model!`

**Comment by pstemarie** [comment]
Can you provide more details - when exactly does this error occur? Screenshot maybe?

**Comment by pstemarie** [comment]
Fixed after conversation with op author in Discord. 

Also fixed the oversized "graphic box" issue (the green box that displays around the earth elemental models in the toolset when selected). This was caused by bad pivots on the various rock meshes. When fixing the pivots, I only centered them to the mesh, I did not align them to the world axis so as not to cause errors in the animation keys.
